[project]
name = "cs-intro-260925"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "RickHsu96", email = "carlhsu1207@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
cs-intro-260925 = "cs_intro_260925:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
